[2025-03-23T17:26:35.054+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T17:26:35.103+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-23T17:18:05.200372+00:00 [queued]>
[2025-03-23T17:26:35.122+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-23T17:18:05.200372+00:00 [queued]>
[2025-03-23T17:26:35.123+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-23T17:26:35.149+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-03-23 17:18:05.200372+00:00
[2025-03-23T17:26:35.162+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=340) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-23T17:26:35.166+0000] {standard_task_runner.py:72} INFO - Started process 342 to run task
[2025-03-23T17:26:35.167+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'submit_spark_job', 'manual__2025-03-23T17:18:05.200372+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmpl5dym4wz']
[2025-03-23T17:26:35.169+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask submit_spark_job
[2025-03-23T17:26:35.274+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-23T17:18:05.200372+00:00 [running]> on host c5bae578e6c2
[2025-03-23T17:26:35.450+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T17:18:05.200372+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T17:18:05.200372+00:00'
[2025-03-23T17:26:35.454+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T17:26:35.499+0000] {base.py:84} INFO - Retrieving connection 'spark_mm'
[2025-03-23T17:26:35.506+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py
[2025-03-23T17:26:38.196+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-23T17:26:40.500+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SparkContext: Running Spark version 3.5.5
[2025-03-23T17:26:40.502+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SparkContext: OS info Linux, 5.15.0-1078-gcp, amd64
[2025-03-23T17:26:40.503+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SparkContext: Java version 17.0.14
[2025-03-23T17:26:40.550+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO ResourceUtils: ==============================================================
[2025-03-23T17:26:40.550+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-23T17:26:40.551+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO ResourceUtils: ==============================================================
[2025-03-23T17:26:40.551+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SparkContext: Submitted application: WeatherDataTransformation
[2025-03-23T17:26:40.582+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-23T17:26:40.595+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO ResourceProfile: Limiting resource is cpu
[2025-03-23T17:26:40.596+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-23T17:26:40.662+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SecurityManager: Changing view acls to: default
[2025-03-23T17:26:40.664+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SecurityManager: Changing modify acls to: default
[2025-03-23T17:26:40.665+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SecurityManager: Changing view acls groups to:
[2025-03-23T17:26:40.665+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SecurityManager: Changing modify acls groups to:
[2025-03-23T17:26:40.666+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-23T17:26:40.979+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:40 INFO Utils: Successfully started service 'sparkDriver' on port 40069.
[2025-03-23T17:26:41.026+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkEnv: Registering MapOutputTracker
[2025-03-23T17:26:41.081+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-23T17:26:41.109+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-23T17:26:41.110+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-23T17:26:41.117+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-23T17:26:41.151+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-5ececfe1-3ab9-482d-81f5-54aee1cf772c
[2025-03-23T17:26:41.171+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-23T17:26:41.207+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-23T17:26:41.411+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-23T17:26:41.518+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-23T17:26:41.586+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkContext: Added JAR /opt/bitnami/spark/jars/postgresql-42.2.23.jar at spark://c5bae578e6c2:40069/jars/postgresql-42.2.23.jar with timestamp 1742750800486
[2025-03-23T17:26:41.586+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkContext: Added JAR /opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar at spark://c5bae578e6c2:40069/jars/spark-3.5-bigquery-0.36.5.jar with timestamp 1742750800486
[2025-03-23T17:26:41.587+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO SparkContext: Added JAR /opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar at spark://c5bae578e6c2:40069/jars/gcs-connector-hadoop3-latest.jar with timestamp 1742750800486
[2025-03-23T17:26:41.709+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-03-23T17:26:41.778+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.5:7077 after 36 ms (0 ms spent in bootstraps)
[2025-03-23T17:26:41.927+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250323172641-0001
[2025-03-23T17:26:41.939+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250323172641-0001/0 on worker-20250323045618-172.18.0.6-39639 (172.18.0.6:39639) with 2 core(s)
[2025-03-23T17:26:41.941+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO StandaloneSchedulerBackend: Granted executor ID app-20250323172641-0001/0 on hostPort 172.18.0.6:39639 with 2 core(s), 1024.0 MiB RAM
[2025-03-23T17:26:41.948+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 38377.
[2025-03-23T17:26:41.949+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO NettyBlockTransferService: Server created on c5bae578e6c2:38377
[2025-03-23T17:26:41.950+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-23T17:26:41.963+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, c5bae578e6c2, 38377, None)
[2025-03-23T17:26:41.970+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManagerMasterEndpoint: Registering block manager c5bae578e6c2:38377 with 434.4 MiB RAM, BlockManagerId(driver, c5bae578e6c2, 38377, None)
[2025-03-23T17:26:41.977+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, c5bae578e6c2, 38377, None)
[2025-03-23T17:26:41.982+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:41 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, c5bae578e6c2, 38377, None)
[2025-03-23T17:26:42.022+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:42 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250323172641-0001/0 is now RUNNING
[2025-03-23T17:26:42.451+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:42 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-03-23T17:26:42.915+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:42 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-23T17:26:42.923+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:42 INFO SharedState: Warehouse path is 'file:/opt/***/spark-warehouse'.
[2025-03-23T17:26:45.517+0000] {spark_submit.py:488} INFO - ERROR:root:Error loading data from PostgreSQL: An error occurred while calling o34.jdbc.
[2025-03-23T17:26:45.519+0000] {spark_submit.py:488} INFO - : org.postgresql.util.PSQLException: ERROR: relation "hourly_data" does not exist
[2025-03-23T17:26:45.520+0000] {spark_submit.py:488} INFO - Position: 15
[2025-03-23T17:26:45.521+0000] {spark_submit.py:488} INFO - at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
[2025-03-23T17:26:45.539+0000] {spark_submit.py:488} INFO - at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
[2025-03-23T17:26:45.541+0000] {spark_submit.py:488} INFO - at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
[2025-03-23T17:26:45.542+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
[2025-03-23T17:26:45.545+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
[2025-03-23T17:26:45.550+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
[2025-03-23T17:26:45.560+0000] {spark_submit.py:488} INFO - at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
[2025-03-23T17:26:45.561+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.getQueryOutputSchema(JDBCRDD.scala:68)
[2025-03-23T17:26:45.569+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:58)
[2025-03-23T17:26:45.571+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:241)
[2025-03-23T17:26:45.576+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:37)
[2025-03-23T17:26:45.585+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:346)
[2025-03-23T17:26:45.586+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-03-23T17:26:45.587+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-03-23T17:26:45.590+0000] {spark_submit.py:488} INFO - at scala.Option.getOrElse(Option.scala:189)
[2025-03-23T17:26:45.591+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-03-23T17:26:45.595+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2025-03-23T17:26:45.602+0000] {spark_submit.py:488} INFO - at org.apache.spark.sql.DataFrameReader.jdbc(DataFrameReader.scala:249)
[2025-03-23T17:26:45.603+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-03-23T17:26:45.604+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-03-23T17:26:45.605+0000] {spark_submit.py:488} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-03-23T17:26:45.605+0000] {spark_submit.py:488} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-03-23T17:26:45.606+0000] {spark_submit.py:488} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-03-23T17:26:45.606+0000] {spark_submit.py:488} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-03-23T17:26:45.607+0000] {spark_submit.py:488} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-03-23T17:26:45.607+0000] {spark_submit.py:488} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-03-23T17:26:45.608+0000] {spark_submit.py:488} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-03-23T17:26:45.608+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-03-23T17:26:45.609+0000] {spark_submit.py:488} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-03-23T17:26:45.609+0000] {spark_submit.py:488} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-03-23T17:26:45.610+0000] {spark_submit.py:488} INFO - 
[2025-03-23T17:26:45.610+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-23T17:26:45.611+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO SparkUI: Stopped Spark web UI at http://c5bae578e6c2:4040
[2025-03-23T17:26:45.617+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-03-23T17:26:45.625+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-03-23T17:26:45.627+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-23T17:26:45.657+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO MemoryStore: MemoryStore cleared
[2025-03-23T17:26:45.659+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO BlockManager: BlockManager stopped
[2025-03-23T17:26:45.664+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-23T17:26:45.671+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-23T17:26:45.686+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:45 INFO SparkContext: Successfully stopped SparkContext
[2025-03-23T17:26:46.106+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:46 INFO ShutdownHookManager: Shutdown hook called
[2025-03-23T17:26:46.107+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-395cfb3b-fdc3-4d32-9d38-45c9579c1bd5
[2025-03-23T17:26:46.115+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-395cfb3b-fdc3-4d32-9d38-45c9579c1bd5/pyspark-8686b6cf-efad-45f9-ae41-fb3b6b31e608
[2025-03-23T17:26:46.122+0000] {spark_submit.py:488} INFO - 25/03/23 17:26:46 INFO ShutdownHookManager: Deleting directory /tmp/spark-72e765f7-b540-4332-9786-d5cf7aab6b4e
[2025-03-23T17:26:46.215+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py. Error code is: 1.
[2025-03-23T17:26:46.223+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=solar_energy_crops_pipeline, task_id=submit_spark_job, run_id=manual__2025-03-23T17:18:05.200372+00:00, execution_date=20250323T171805, start_date=20250323T172635, end_date=20250323T172646
[2025-03-23T17:26:46.278+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T17:26:46.279+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task submit_spark_job (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py. Error code is: 1.; 342)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.master=spark://spark-master:7077 --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.fs.AbstractFileSystem.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS --jars /opt/bitnami/spark/jars/postgresql-42.2.23.jar,/opt/bitnami/spark/jars/spark-3.5-bigquery-0.36.5.jar,/opt/bitnami/spark/jars/gcs-connector-hadoop3-latest.jar --name arrow-spark jobs/transform.py. Error code is: 1.
[2025-03-23T17:26:46.301+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-23T17:26:46.346+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T17:26:46.352+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
