[2025-03-14T18:47:59.108+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T18:47:59.136+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-09T19:18:27.013364+00:00 [queued]>
[2025-03-14T18:47:59.212+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-09T19:18:27.013364+00:00 [queued]>
[2025-03-14T18:47:59.213+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 4
[2025-03-14T18:47:59.240+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2025-03-09 19:18:27.013364+00:00
[2025-03-14T18:47:59.574+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T18:47:59.808+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2025-03-14T18:47:59.819+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'submit_spark_job', 'manual__2025-03-09T19:18:27.013364+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmpxzpx256b']
[2025-03-14T18:47:59.905+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask submit_spark_job
[2025-03-14T18:48:00.916+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.submit_spark_job manual__2025-03-09T19:18:27.013364+00:00 [running]> on host 87bb601a2791
[2025-03-14T18:48:02.251+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T19:18:27.013364+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T19:18:27.013364+00:00'
[2025-03-14T18:48:02.254+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T18:48:02.334+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-03-14T18:48:02.340+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --conf spark.master=spark://spark-master:7077 --packages org.postgresql:postgresql:42.2.5 --name arrow-spark ./dags/transform.py
[2025-03-14T18:48:22.299+0000] {spark_submit.py:488} INFO - :: loading settings :: url = jar:file:/home/***/.local/lib/python3.12/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-03-14T18:48:22.910+0000] {spark_submit.py:488} INFO - Ivy Default Cache set to: /home/***/.ivy2/cache
[2025-03-14T18:48:22.911+0000] {spark_submit.py:488} INFO - The jars for the packages stored in: /home/***/.ivy2/jars
[2025-03-14T18:48:22.999+0000] {spark_submit.py:488} INFO - org.postgresql#postgresql added as a dependency
[2025-03-14T18:48:23.001+0000] {spark_submit.py:488} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-a86f3814-94d5-4fcc-bc74-d76414a79701;1.0
[2025-03-14T18:48:23.002+0000] {spark_submit.py:488} INFO - confs: [default]
[2025-03-14T18:48:30.507+0000] {spark_submit.py:488} INFO - found org.postgresql#postgresql;42.2.5 in central
[2025-03-14T18:48:30.869+0000] {spark_submit.py:488} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar ...
[2025-03-14T18:48:32.903+0000] {spark_submit.py:488} INFO - :: resolution report :: resolve 7683ms :: artifacts dl 2302ms
[2025-03-14T18:48:32.907+0000] {spark_submit.py:488} INFO - :: modules in use:
[2025-03-14T18:48:32.909+0000] {spark_submit.py:488} INFO - org.postgresql#postgresql;42.2.5 from central in [default]
[2025-03-14T18:48:32.910+0000] {spark_submit.py:488} INFO - ---------------------------------------------------------------------
[2025-03-14T18:48:32.911+0000] {spark_submit.py:488} INFO - |                  |            modules            ||   artifacts   |
[2025-03-14T18:48:32.911+0000] {spark_submit.py:488} INFO - |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-03-14T18:48:32.912+0000] {spark_submit.py:488} INFO - ---------------------------------------------------------------------
[2025-03-14T18:48:32.913+0000] {spark_submit.py:488} INFO - |      default     |   1   |   1   |   1   |   0   ||   1   |   0   |
[2025-03-14T18:48:32.913+0000] {spark_submit.py:488} INFO - ---------------------------------------------------------------------
[2025-03-14T18:48:32.914+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:32.914+0000] {spark_submit.py:488} INFO - :: problems summary ::
[2025-03-14T18:48:32.915+0000] {spark_submit.py:488} INFO - :::: WARNINGS
[2025-03-14T18:48:32.915+0000] {spark_submit.py:488} INFO - [FAILED     ] org.postgresql#postgresql;42.2.5!postgresql.jar(bundle): Downloaded file size (0) doesn't match expected Content Length (825943) for https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar. Please retry. (2298ms)
[2025-03-14T18:48:32.915+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:32.916+0000] {spark_submit.py:488} INFO - [FAILED     ] org.postgresql#postgresql;42.2.5!postgresql.jar(bundle): Downloaded file size (0) doesn't match expected Content Length (825943) for https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar. Please retry. (2298ms)
[2025-03-14T18:48:32.916+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:32.917+0000] {spark_submit.py:488} INFO - ==== central: tried
[2025-03-14T18:48:32.917+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:32.999+0000] {spark_submit.py:488} INFO - https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.5/postgresql-42.2.5.jar
[2025-03-14T18:48:33.002+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.005+0000] {spark_submit.py:488} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-03-14T18:48:33.006+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.007+0000] {spark_submit.py:488} INFO - ::              FAILED DOWNLOADS            ::
[2025-03-14T18:48:33.007+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.008+0000] {spark_submit.py:488} INFO - :: ^ see resolution messages for details  ^ ::
[2025-03-14T18:48:33.008+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.009+0000] {spark_submit.py:488} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-03-14T18:48:33.009+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.010+0000] {spark_submit.py:488} INFO - :: org.postgresql#postgresql;42.2.5!postgresql.jar(bundle)
[2025-03-14T18:48:33.011+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.011+0000] {spark_submit.py:488} INFO - ::::::::::::::::::::::::::::::::::::::::::::::
[2025-03-14T18:48:33.012+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.012+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.015+0000] {spark_submit.py:488} INFO - 
[2025-03-14T18:48:33.016+0000] {spark_submit.py:488} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-03-14T18:48:33.016+0000] {spark_submit.py:488} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: org.postgresql#postgresql;42.2.5!postgresql.jar(bundle)]
[2025-03-14T18:48:33.017+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1613)
[2025-03-14T18:48:33.017+0000] {spark_submit.py:488} INFO - at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-03-14T18:48:33.018+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:339)
[2025-03-14T18:48:33.019+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:969)
[2025-03-14T18:48:33.020+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:199)
[2025-03-14T18:48:33.099+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:222)
[2025-03-14T18:48:33.100+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2025-03-14T18:48:33.101+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-03-14T18:48:33.102+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-03-14T18:48:33.102+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-03-14T18:48:33.202+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --conf spark.master=spark://spark-master:7077 --packages org.postgresql:postgresql:42.2.5 --name arrow-spark ./dags/transform.py. Error code is: 1.
[2025-03-14T18:48:33.214+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_energy_crops_pipeline, task_id=submit_spark_job, run_id=manual__2025-03-09T19:18:27.013364+00:00, execution_date=20250309T191827, start_date=20250314T184759, end_date=20250314T184833
[2025-03-14T18:48:34.309+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T18:48:34.311+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task submit_spark_job (Cannot execute: spark-submit --master spark-master:7077 --conf spark.master=spark://spark-master:7077 --packages org.postgresql:postgresql:42.2.5 --name arrow-spark ./dags/transform.py. Error code is: 1.; 75)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --conf spark.master=spark://spark-master:7077 --packages org.postgresql:postgresql:42.2.5 --name arrow-spark ./dags/transform.py. Error code is: 1.
[2025-03-14T18:48:34.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-14T18:48:34.601+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T18:48:34.606+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
