[2025-03-02T10:21:34.489+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T10:21:34.531+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T10:21:34.551+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T10:21:34.553+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-02T10:21:34.628+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-01 00:00:00+00:00
[2025-03-02T10:21:34.681+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T10:21:34.691+0000] {standard_task_runner.py:72} INFO - Started process 94 to run task
[2025-03-02T10:21:34.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'extract_data', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmpnukkpi1p']
[2025-03-02T10:21:34.713+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask extract_data
[2025-03-02T10:21:35.130+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.extract_data scheduled__2025-03-01T00:00:00+00:00 [running]> on host 31ff978c4ca8
[2025-03-02T10:21:38.604+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-02T10:21:38.606+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T10:21:38.670+0000] {logging_mixin.py:190} INFO - Extracting data from API...
[2025-03-02T10:21:38.674+0000] {logging_mixin.py:190} INFO - In Asynchronus function
[2025-03-02T10:21:41.963+0000] {logging_mixin.py:190} INFO - Done fetching all years!
[2025-03-02T10:21:41.964+0000] {logging_mixin.py:190} INFO - Extraction completed
[2025-03-02T10:21:43.180+0000] {logging_mixin.py:190} INFO - Error saving data to PostgreSQL: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(hourly_data, 2200) already exists.

[SQL: 
CREATE TABLE hourly_data (
	time TEXT, 
	temperature_2m FLOAT(53), 
	relative_humidity_2m BIGINT, 
	dew_point_2m FLOAT(53), 
	precipitation_probability TEXT, 
	precipitation FLOAT(53), 
	rain FLOAT(53), 
	pressure_msl FLOAT(53), 
	surface_pressure FLOAT(53), 
	cloud_cover BIGINT, 
	wind_speed_10m FLOAT(53), 
	wind_direction_10m BIGINT, 
	soil_temperature_6cm TEXT, 
	soil_temperature_18cm TEXT, 
	soil_moisture_0_to_1cm TEXT, 
	soil_moisture_3_to_9cm TEXT, 
	is_day BIGINT, 
	sunshine_duration FLOAT(53), 
	direct_radiation FLOAT(53), 
	diffuse_radiation FLOAT(53), 
	"Time_Units" TEXT, 
	temperature_2m_unit TEXT, 
	relative_humidity_2m_unit TEXT, 
	dew_point_2m_unit TEXT, 
	precipitation_probability_unit TEXT, 
	precipitation_unit TEXT, 
	rain_unit TEXT, 
	pressure_msl_unit TEXT, 
	surface_pressure_unit TEXT, 
	cloud_cover_unit TEXT, 
	wind_speed_10m_unit TEXT, 
	wind_direction_10m_unit TEXT, 
	soil_temperature_6cm_unit TEXT, 
	soil_temperature_18cm_unit TEXT, 
	soil_moisture_0_to_1cm_unit TEXT, 
	soil_moisture_3_to_9cm_unit TEXT, 
	is_day_unit TEXT, 
	sunshine_duration_unit TEXT, 
	direct_radiation_unit TEXT, 
	diffuse_radiation_unit TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2025-03-02T10:21:43.291+0000] {logging_mixin.py:190} INFO - Data saved to PostgreSQL table: solar_crops_raw
[2025-03-02T10:21:43.293+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-02T10:21:43.308+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T10:21:43.310+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=solar_energy_crops_pipeline, task_id=extract_data, run_id=scheduled__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250302T102134, end_date=20250302T102143
[2025-03-02T10:21:43.355+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-02T10:21:43.377+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T10:21:43.383+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
