[2025-03-02T19:35:23.548+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T19:35:23.564+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data manual__2025-03-02T19:35:21.345441+00:00 [queued]>
[2025-03-02T19:35:23.573+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.extract_data manual__2025-03-02T19:35:21.345441+00:00 [queued]>
[2025-03-02T19:35:23.574+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-03-02T19:35:23.590+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_data> on 2025-03-02 19:35:21.345441+00:00
[2025-03-02T19:35:23.597+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=971) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T19:35:23.599+0000] {standard_task_runner.py:72} INFO - Started process 973 to run task
[2025-03-02T19:35:23.598+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'extract_data', 'manual__2025-03-02T19:35:21.345441+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmp_o6w9_ak']
[2025-03-02T19:35:23.601+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask extract_data
[2025-03-02T19:35:23.660+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.extract_data manual__2025-03-02T19:35:21.345441+00:00 [running]> on host 7465e3cb0781
[2025-03-02T19:35:23.753+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T19:35:21.345441+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T19:35:21.345441+00:00'
[2025-03-02T19:35:23.755+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-02T19:35:23.767+0000] {logging_mixin.py:190} INFO - Extracting data from API...
[2025-03-02T19:35:23.770+0000] {logging_mixin.py:190} INFO - Fetching data for year 1967
[2025-03-02T19:35:25.302+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-02T19:35:55.316+0000] {logging_mixin.py:190} INFO - Fetching data for year 1968
[2025-03-02T19:35:56.636+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-02T19:36:26.648+0000] {logging_mixin.py:190} INFO - Fetching data for year 1969
[2025-03-02T19:36:28.070+0000] {logging_mixin.py:190} INFO - Sleeping for a while to respect API rate limits...
[2025-03-02T19:36:34.309+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-03-02T19:36:34.310+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-02T19:36:34.312+0000] {process_utils.py:132} INFO - Sending 15 to group 973. PIDs of all processes in the group: [973]
[2025-03-02T19:36:34.313+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 973
[2025-03-02T19:36:34.313+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-02T19:36:34.342+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-02T19:36:34.366+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=973, status='terminated', exitcode=0, started='19:35:23') (973) terminated with exit code 0
