[2025-03-15T18:06:43.692+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T18:06:43.761+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:06:36.502525+00:00 [queued]>
[2025-03-15T18:06:43.779+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:06:36.502525+00:00 [queued]>
[2025-03-15T18:06:43.780+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T18:06:43.984+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): first_task> on 2025-03-15 18:06:36.502525+00:00
[2025-03-15T18:06:44.082+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T18:06:44.084+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'solar_energy_crops_pipeline', 'first_task', 'manual__2025-03-15T18:06:36.502525+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/mainDag.py', '--cfg-path', '/tmp/tmpaopp6iy_']
[2025-03-15T18:06:44.161+0000] {standard_task_runner.py:72} INFO - Started process 86 to run task
[2025-03-15T18:06:44.161+0000] {standard_task_runner.py:105} INFO - Job 107: Subtask first_task
[2025-03-15T18:06:44.367+0000] {task_command.py:467} INFO - Running <TaskInstance: solar_energy_crops_pipeline.first_task manual__2025-03-15T18:06:36.502525+00:00 [running]> on host 13d41feaf433
[2025-03-15T18:06:44.601+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='solar_energy_crops_pipeline' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T18:06:36.502525+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T18:06:36.502525+00:00'
[2025-03-15T18:06:44.603+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T18:06:44.688+0000] {base.py:84} INFO - Retrieving connection 'spark_mm'
[2025-03-15T18:06:44.693+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark Script1.py
[2025-03-15T18:06:58.763+0000] {spark_submit.py:488} INFO - python3: can't open file '/opt/***/Script1.py': [Errno 2] No such file or directory
[2025-03-15T18:06:58.791+0000] {spark_submit.py:488} INFO - 25/03/15 18:06:58 INFO ShutdownHookManager: Shutdown hook called
[2025-03-15T18:06:58.797+0000] {spark_submit.py:488} INFO - 25/03/15 18:06:58 INFO ShutdownHookManager: Deleting directory /tmp/spark-2c8fabd2-26a2-4541-935e-04eeed77f284
[2025-03-15T18:06:58.908+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark Script1.py. Error code is: 2.
[2025-03-15T18:06:58.940+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=solar_energy_crops_pipeline, task_id=first_task, run_id=manual__2025-03-15T18:06:36.502525+00:00, execution_date=20250315T180636, start_date=20250315T180643, end_date=20250315T180658
[2025-03-15T18:06:59.035+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T18:06:59.036+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 107 for task first_task (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark Script1.py. Error code is: 2.; 86)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark Script1.py. Error code is: 2.
[2025-03-15T18:06:59.084+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-15T18:06:59.152+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T18:06:59.158+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-15T18:06:59.167+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
